language: java
jdk:
  - openjdk8
env:
  global:
    - CODECOV_TOKEN='42659dcd-9113-447f-ba16-1dacf5fc0ec6'
before_install:
  - pip install codecov
  - pip install coverage
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn test
after_success:
  - codecov
